### ISSUE TITLE
Hey jack can u help me?

### ISSUE THREAD

**Issue by dyarfaradj** [jackyzyb/Tetris#1]
,,,

**Comment by jackyzyb** [comment]
Sure! I’m glad to help:)

**Comment by mrkiller2010** [comment]
Do you have discord, skype or anything we can chat directly through? I need some help with assembly and I thought since you're familiar with PIC18F4520 you could help me out :)

**Comment by jackyzyb** [comment]
Yes Skype works for me. But ahead of it could you please tell me a little bit about yourself?

On 12 Feb 2018, at 12:22 PM, mrkiller2010 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have discord, skype or anything we can chat directly through? I need some help with assembly and I thought since you're familiar with PIC18F4520 you could help me out :)

**Comment by mrkiller2010** [comment]
Yeah sure, I'm studying computer science and have a course in embedded systems and we're currently learning pic asm. I've been doing well in this course however I've ran into few issues with interrupts configuration etc..

**Comment by jackyzyb** [comment]
Great! I’m a junior student major in CS. Here is my Skype link:
https://join.skype.com/invite/Oc6c5pcTEXN6
On 12 Feb 2018, at 12:33 PM, mrkiller2010 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah sure, I'm studying computer science and have a course in embedded systems and we're currently learning pic asm. I've been doing well in this course however I've ran into few issues with interrupts configuration etc..
